version: "3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - airflow

networks:
  airflow:
    name: airflow_default
    external: true
